version: "3.9"

services:
  backend:
    build: ./server
    container_name: expense-backend
    restart: always
    ports:
      - "5001:5000"
    env_file:
      - ./server/.env
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: expense-frontend
    restart: always
    ports:
      - "3003:80"
    env_file:
      - ./client/.env
    networks:
      - app-network

networks:
  app-network:
    external: true